/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
/work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py:109: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.nn.functional.softmax(output)
