#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename

#SBATCH --time=24:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=1  # 16 processor core(s) per node 
#SBATCH --gres=gpu:a100:1
#SBATCH --cpus-per-task=8
#SBATCH --partition=gpu    # gpu node(s)
#SBATCH --job-name="calculate accuracies for resnet and vgg"
#SBATCH --mail-user=msaadati@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=slurm-%j.out # job standard output file (%j replaced by job id)
#SBATCH --error="training.e" # job standard error file (%j replaced by job id)

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load miniconda3
source activate iNatSoftware

#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_0outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_0inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_0inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_0inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_0
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_1
srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_2
srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_3
srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_4
srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_5
srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_6
srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_7
srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_8
srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_9
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_10outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_10inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_10inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_10inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_10
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_20outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_20inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_20inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_20inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_20
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_30outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_30inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_30inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_30inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_30
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_40outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_40inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_40inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_40inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_40
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_49outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_49inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_49inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/model_49inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/MAH_results_nonInsecta2526 --checkpoints model_49



#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_0outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_0inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_0inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_0inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/MAH_results_nonInsecta2526 --checkpoints model_0
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/MAH_results_nonInsecta2526 --checkpoints model_1
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_10outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_10inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_10inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_10inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/MAH_results_nonInsecta2526 --checkpoints model_10
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_20outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_20inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_20inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_20inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/MAH_results_nonInsecta2526 --checkpoints model_20
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_30outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_30inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_30inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_30inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/MAH_results_nonInsecta2526 --checkpoints model_30
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_40outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_40inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_40inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_40inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/MAH_results_nonInsecta2526 --checkpoints model_40
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_49outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_49inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_49inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/model_49inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/MAH_results_nonInsecta2526 --checkpoints model_49



#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_0outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_0inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_0inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_0inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/MAH_results_nonInsecta2526 --checkpoints model_0
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_1outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_1inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_1inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_1inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/MAH_results_nonInsecta2526 --checkpoints model_1
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_10outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_10inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_10inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_10inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/MAH_results_nonInsecta2526 --checkpoints model_10
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_49outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_49inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_49inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/model_49inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/MAH_results_nonInsecta2526 --checkpoints model_49

# Balanced vs Unbalanced:
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_b/prelogits/model_49outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_b/prelogits/model_49inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_b/prelogits/model_49inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_b/prelogits/model_49inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_b/MAH_results_nonInsecta2526/ --checkpoints model_49
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub/prelogits/model_49outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub/prelogits/model_49inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub/prelogits/model_49inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub/prelogits/model_49inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub/MAH_results_nonInsecta2526/ --checkpoints model_49
#srun python /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/Mahalanobis_distance.py --outDistValid-embeds  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub_uniform/prelogits/model_49outDistValid_embeds.pt --inDistValid-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub_uniform/prelogits/model_49inDistValid_embeds.pt --inDistTrain-embeds /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub_uniform/prelogits/model_49inDistTrain_embeds.pt --inDistTrain-labels /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub_uniform/prelogits/model_49inDistTrain_labels.pt --MAH-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32_balancedSubset_ub_uniform/MAH_results_nonInsecta2526/ --checkpoints model_49
