#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename

#SBATCH --time=24:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=8  # 16 processor core(s) per node 
#SBATCH --gres=gpu:a100:1
#SBATCH --partition=gpu    # gpu node(s)
#SBATCH --job-name="calculate accuracies for resnet and vgg"
#SBATCH --mail-user=msaadati@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=slurm-%j.out # job standard output file (%j replaced by job id)
#SBATCH --error="training.e" # job standard error file (%j replaced by job id)

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load miniconda3
source activate iNatSoftware

#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitEdited.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_0.pth --checkpoints  model_0  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/ --model regnet32
#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitEdited.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_1.pth --checkpoints  model_1  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/ --model regnet32
#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitEdited.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_10.pth --checkpoints  model_10  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/ --model regnet32
#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitEdited.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_49.pth --checkpoints  model_49  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/prelogits/ --model regnet32

#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitEdited.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_0.pth --checkpoints  model_0  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/ --model resnet50
#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitEdited.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_1.pth --checkpoints  model_1  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/ --model resnet50
srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitEdited.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_10.pth --checkpoints  model_10  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/ --model resnet50
srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitEdited.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet32-142/checkpoints/model_49.pth --checkpoints  model_49  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/prelogits/ --model resnet50

#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitVGG.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/model_0.pth --checkpoints  model_0  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/ --model VGG
#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitVGG.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/model_1.pth --checkpoints  model_1  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/ --model VGG
#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitVGG.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/model_10.pth --checkpoints  model_10  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/ --model VGG
#srun python  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/extract_prelogitVGG.py  --indist-train-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_train50/   --indist-test-path  /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/OOD_valid50/ --outdist-test-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Data/out-distribution/noninsecta-2526c-valid/  --model-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/model_49.pth --checkpoints  model_49  --logits-path /work/baskarg/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/prelogits/ --model VGG

