#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename

#SBATCH --time=24:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-gpu=1
#SBATCH --gres=gpu:a100:1
#SBATCH --partition=priority-a100    # gpu node(s)
#SBATCH --account=baskargroup-a100gpu
#SBATCH --job-name="calculate accuracies for resnet and vgg"
#SBATCH --mail-user=msaadati@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=slurm-%j.out # job standard output file (%j replaced by job id)
#SBATCH --error="training.e" # job standard error file (%j replaced by job id)

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load miniconda3
source activate iNatSoftware

#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_0.pth --model regnet32 --checkpoints model_0
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_1.pth --model regnet32 --checkpoints model_1
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_2.pth --model regnet32 --checkpoints model_2
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_3.pth --model regnet32 --checkpoints model_3
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_4.pth --model regnet32 --checkpoints model_4
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_5.pth --model regnet32 --checkpoints model_5
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_6.pth --model regnet32 --checkpoints model_6
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_7.pth --model regnet32 --checkpoints model_7
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_8.pth --model regnet32 --checkpoints model_8
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_9.pth --model regnet32 --checkpoints model_9
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_10.pth --model regnet32 --checkpoints model_10
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_20.pth --model regnet32 --checkpoints model_20
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_30.pth --model regnet32 --checkpoints model_30
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_40.pth --model regnet32 --checkpoints model_40
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Regnet32-142/checkpoints/model_49.pth --model regnet32 --checkpoints model_49



#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_0.pth --model resnet50 --checkpoints model_0
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_1.pth --model resnet50 --checkpoints model_1
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_2.pth --model resnet50 --checkpoints model_2
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_3.pth --model resnet50 --checkpoints model_3
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_4.pth --model resnet50 --checkpoints model_4
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_5.pth --model resnet50 --checkpoints model_5
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_6.pth --model resnet50 --checkpoints model_6
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_7.pth --model resnet50 --checkpoints model_7
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_8.pth --model resnet50 --checkpoints model_8
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_9.pth --model resnet50 --checkpoints model_9
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_10.pth --model resnet50 --checkpoints model_10
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_20.pth --model resnet50 --checkpoints model_20
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_30.pth --model resnet50 --checkpoints model_30
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_40.pth --model resnet50 --checkpoints model_40
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/train_classifiers/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/accuracies.csv --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/Resnet50-142/checkpoints/model_49.pth --model resnet50 --checkpoints model_49


#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/accuracies.txt --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/model_0.pth --model VGG --checkpoints model_0
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/accuracies.txt --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/model_1.pth --model VGG --checkpoints model_1
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/accuracies.txt --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/model_10.pth --model VGG --checkpoints model_10
#srun python /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Codes/OOD_methods/ModelAccuracyReport.py --test-data /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Data/in-distribution/iNat_ISU142/val/ --result-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/accuracies.txt --model-path /work/mech-ai/Mojdeh/iNat_Project-mini-Insecta-2021/Models/VGG-142/checkpoints/model_49.pth --model VGG --checkpoints model_49
